### ISSUE TITLE
Reporting seems to not work 

### ISSUE THREAD

**Issue by akuryan** [JetBrains/TeamCity.ServiceMessages#13]
I am trying to report some statistical values for Teamcity using this library from my custom MsBuild task.
If I am launching my task in Debug (without teamcity) - I see service messages outputted to console. But the problem is in Teamcity (9.0.1) - which seems to ignore them (but i do not see them in build log).
I am trying to see this message in my statistics:
            using (var messages = new TeamCityServiceMessages().CreateWriter())
            {
                messages.WriteBuildStatistics("chartingTeamcityBlaBlaBla", "33");
            }

If I will add 
'TeamCityReportStatsValue Key='chart2Key' Value='21' ' to my custom MsBuild Target  - this statistical value is not present :(.
Can you advise me what is wrong?

**Comment by NikolayPianikov** [comment]
@akuryan sorry for delay :) but is it actual issue?

**Comment by akuryan** [comment]
It was at time being. For now - I am just righting text strings to output

**Comment by NikolayPianikov** [comment]
@akuryan  I've closed this issue, feel free to reopened if it is reproduced
