### ISSUE TITLE
.NET 4.6 throws System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by curdincaspar** [JetBrains/TeamCity.ServiceMessages#19]
The following exception is thrown when this library is used with net46:

> System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by NikolayPianikov** [comment]
@curdincaspar, unfortunately the suggested sample uses code which was implemented without taking in account backward compatibility of console IO operations. We supposed that we will have only one package for net45 and higher. So try using updated sample (line `using (var writer = new TeamCityServiceMessages().CreateWriter(str => Console.WriteLine(str))`), I think it solves your issue

**Comment by NikolayPianikov** [comment]
Workaround is to use code `using (var writer = new TeamCityServiceMessages().CreateWriter(str => Console.WriteLine(str)))` for creating an writer

**Comment by curdincaspar** [comment]
Thank you, this way it works.
