### ISSUE TITLE
Unable to attach test metadata

### ISSUE THREAD

**Issue by olsh** [JetBrains/TeamCity.ServiceMessages#27]
We are using TeamCity 2018.2.1 and VSTest test step with NUnit 3.
I'm trying to attach metadata with the following code on `TearDown` step:

```csharp
using (var writer = new TeamCityServiceMessages().CreateWriter())
{
    using (var teamCityTestWriter = writer.OpenTest(TestContext.CurrentContext.Test.FullName))
    {
        // The text is rendered in the build log
        teamCityTestWriter.WriteStdOutput("Trying to save test screenshot");
        
        // These lines doesn't work
        teamCityTestWriter.WriteValue(TestContext.CurrentContext.Test.ID, "TestId");
        teamCityTestWriter.WriteImage($"{screenshotsDirectory}/{imageName}");
    }
}
```

And I can't get the metadata attached to the Test in TeamCity. Only `WriteStdOutput` method works in my case.

According to [this documentation](https://confluence.jetbrains.com/display/TCD18/Reporting+Test+Metadata#ReportingTestMetadata-Reportingadditionaltestdata), I should pass full test method name to the `testName` property.
So, I've tried to pass `Namespace.ClassName.TestName`, `ClassName.TestName` and `TestName` in the `OpenTest` method, nothing works.

The image which I'm trying to attach is accessible via artifacts.

What do I do wrong?

**Comment by NikolayPianikov** [comment]
@olsh at first you should publish image as artifact and after that you can send image as a link to this artifact. See [this example](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter/blob/91cb9597560817221af7e8bcc1d819efd6163950/TeamCity.VSTest.TestLogger/MessageHandler.cs#L127)

**Comment by olsh** [comment]
Hi @NikolayPianikov,

Thanks for the answer! Tried that, but still doesn't work. Also, I've tried to attach the image to `TestContext` using [`AddTestAttachment`](https://github.com/nunit/docs/wiki/TestContext#addtestattachment-37) method, this neither works.

Also, what about this line?
```csharp
teamCityTestWriter.WriteValue(TestContext.CurrentContext.Test.ID, "TestId");
```

The value doesn't need an artifact but doesn't work too.

**Comment by NikolayPianikov** [comment]
I've update samples [here](https://github.com/JetBrains/TeamCity.ServiceMessages). 
You can attach test metadata to tests only. For instance these service messages attach `TeamCity.png` to test named `Image`:

```
##teamcity[testStarted name='Image' captureStandardOutput='false' timestamp='2019-01-15T13:34:30.203+0000' flowId='1']
##teamcity[publishArtifacts 'C:\Projects\TeamCity\TeamCity.ServiceMessages\Samples\Simple\bin\Debug\net45\TeamCity.png => TestData']
##teamcity[testMetadata testName='Image' type='image' value='TestData/TeamCity.png' name='Team City Logo' timestamp='2019-01-15T13:34:30.206+0000' flowId='1']
##teamcity[testFinished name='Image' timestamp='2019-01-15T13:34:30.206+0000' flowId='1']
```

Thus If you created some test item for your `TearDown` it would be possible to link metadata to it.

Could you share your generated TeamCity service messages for `value` case? For the following code
```scharp
// Attaching a value to test
using (var test = testClass.OpenTest("Value"))
{
  test.WriteValue(1234.56.ToString(CultureInfo.InvariantCulture), "Some Value");
}
```
I've got:

```
##teamcity[testStarted name='Value' captureStandardOutput='false' timestamp='2019-01-15T13:34:30.206+0000' flowId='1']
##teamcity[testMetadata testName='Value' value='1234.56' name='Some Value' timestamp='2019-01-15T13:34:30.207+0000' flowId='1']
##teamcity[testFinished name='Value' timestamp='2019-01-15T13:34:30.207+0000' flowId='1']
```

and it looks good in the build log

**Comment by NikolayPianikov** [comment]
By the way if you are using `Microsoft.NET.Sdk` for `nunut` you could use code like here:
``` csharp
[Test]
public void Test1()
{
  TestContext.AddTestAttachment(@"abc.jpg");
}

public TestContext TestContext { get; set; }
```

[Tests.zip](https://github.com/JetBrains/TeamCity.ServiceMessages/files/2759972/Tests.zip)

TeamCity dotnet CLI runner helps you to get a result easy via command `dotnet test`

**Comment by olsh** [comment]
I just copied the example from the readme, `teamCityTestWriter.WriteStdOutput` and `writer.PublishArtifact` works as expected, but the Metadata isn't attached:

```csharp
using (var writer = new TeamCityServiceMessages().CreateWriter())
{
    using (var block = writer.OpenBlock("Tests"))
    {
        using (var openTestSuite = block.OpenTestSuite("CheckoutTests"))
        {
            using (var teamCityTestWriter = openTestSuite.OpenTest("PassCheckout_order_all_services_success_for_Ontario"))
            {
                teamCityTestWriter.WriteStdOutput($"Trying to save test screenshot for tear down test {TestContext.CurrentContext.Test.FullName}");

                writer.PublishArtifact(imagePath + " => TestData");

                teamCityTestWriter.WriteValue(TestContext.CurrentContext.Test.ID, "TestId");
                teamCityTestWriter.WriteImage($"TestData/{imageName}", "Tear down Uploading");
            }
        }
    }
}
```

TC Log:

```
[12:38:17] :	 [Step 16/16] Standard Output Messages:
[12:38:17] :	 [Step 16/16]  
[12:38:17] :	 [Step 16/16] Tests
[12:38:17] :	 [Step 16/16]  
[12:38:17] :		 [Tests] CheckoutTests
[12:38:17] :	 [Step 16/16]  
[12:38:17] :			 [CheckoutTests] PassCheckout_order_all_services_success_for_Ontario
[12:38:17] :	 [Step 16/16]  
[12:38:17] :				 [PassCheckout_order_all_services_success_for_Ontario] [Test Output]
Trying to save test screenshot for test VMedia.Web.Mobile.UiTests.CheckoutTests.PassCheckout_order_all_services_success_for_Ontario
[12:38:17] :	 [Step 16/16] Publishing artifacts (3s)
[12:38:17] :		 [Publishing artifacts] Collecting files to publish: [D:\BuildAgent\work\d9ad44e0ed3e8e7\src\VMedia.Web.Mobile.UiTests\bin\Release\UiTestScreenshots\19-01-16-09-37-16-642_screen.png => TestData]
[12:38:20] :		 [Publishing artifacts] Publishing 1 file using [ArtifactsCachePublisher]: src/VMedia.Web.Mobile.UiTests/bin/Release/UiTestScreenshots/19-01-16-09-37-16-642_screen.png => TestData
[12:38:20] :		 [Publishing artifacts] Publishing 1 file using [WebPublisher]: src/VMedia.Web.Mobile.UiTests/bin/Release/UiTestScreenshots/19-01-16-09-37-16-642_screen.png => TestData
[12:38:17] :	 [Step 16/16]  
[12:38:17]i:	 [Step 16/16] ##teamcity[publishArtifacts 'D:\BuildAgent\work\d9ad44e0ed3e8e7\src\VMedia.Web.Mobile.UiTests\bin\Release\UiTestScreenshots\19-01-16-09-37-16-642_screen.png => TestData']
[12:38:17] :	 [Step 16/16]  
[12:38:17] :	 [Step 16/16]  
[12:38:17] :	 [Step 16/16]  
[12:38:17] :	 [Step 16/16]  
[12:38:17] :	 [Step 16/16]  
[12:38:17] :	 [Step 16/16]  
```

> By the way if you are using Microsoft.NET.Sdk for nunut you could use code like here:

We are using `NUnit3TestAdapter` and `NUnit` only.

**Comment by NikolayPianikov** [comment]
@olsh could you change `writer` like here and attach `log.txt` containing a complete set of TeamCity service messages?

```csharp
using (var writer = new TeamCityServiceMessages().CreateWriter(line => File.AppendAllText("log.txt", line)))
```

Also make sure you have got the artifact like `TestData/19-01-16-09-37-16-642_screen.png` for the appropriate build.

**Comment by olsh** [comment]
@NikolayPianikov 

> @olsh could you change writer like here and attach log.txt containing a complete set of TeamCity service messages?

```
##teamcity[blockOpened name='Tests' timestamp='2019-01-17T12:50:52.705+0000' flowId='1']
##teamcity[testSuiteStarted name='CheckoutTests' timestamp='2019-01-17T12:50:52.711+0000' flowId='1']
##teamcity[testStarted name='PassCheckout_order_all_services_success_for_Ontario' captureStandardOutput='false' timestamp='2019-01-17T12:50:52.712+0000' flowId='1']
##teamcity[testStdOut name='PassCheckout_order_all_services_success_for_Ontario' out='Trying to save test screenshot for tear down test VMedia.Web.Mobile.UiTests.CheckoutTests.PassCheckout_order_all_services_success_for_Ontario' tc:tags='tc:parseServiceMessagesInside' timestamp='2019-01-17T12:50:52.713+0000' flowId='1']
##teamcity[publishArtifacts 'C:\projects\vmedia-web\src\VMedia.Web.Mobile.UiTests\bin\Debug\PassCheckout_order_all_services_success_for_Ontario_19-01-17-12-50-52-635.png => TestData']
##teamcity[testMetadata testName='PassCheckout_order_all_services_success_for_Ontario' value='0-1013' name='TestId' timestamp='2019-01-17T12:50:52.714+0000' flowId='1']
##teamcity[testMetadata testName='PassCheckout_order_all_services_success_for_Ontario' type='image' value='TestData/PassCheckout_order_all_services_success_for_Ontario_19-01-17-12-50-52-635.png' name='Tear down Uploading' timestamp='2019-01-17T12:50:52.715+0000' flowId='1']
##teamcity[testFinished name='PassCheckout_order_all_services_success_for_Ontario' timestamp='2019-01-17T12:50:52.716+0000' flowId='1']
##teamcity[testSuiteFinished name='CheckoutTests' timestamp='2019-01-17T12:50:52.716+0000' flowId='1']
##teamcity[blockClosed name='Tests' timestamp='2019-01-17T12:50:52.717+0000' flowId='1']
```

> Also make sure you have got the artifact like TestData/19-01-16-09-37-16-642_screen.png for the appropriate build.

Yes, the file is in the `Artifacts` tab.

**Comment by NikolayPianikov** [comment]
@olsh thank you

**Comment by NikolayPianikov** [comment]
@olsh could you use [WriteFile](https://github.com/JetBrains/TeamCity.ServiceMessages/blob/09da936f83ad40a84c7f2f5cb5dea0705b13c710/Samples/Simple/Program.cs#L51) instead `WriteImage` method instead. Does it attach a file to your test?

**Comment by olsh** [comment]
Sorry for the late response.
WriteFile doesn't work either.

**Comment by NikolayPianikov** [comment]
Could you do the following:
- Unpack [image.zip](https://github.com/JetBrains/TeamCity.ServiceMessages/files/2791776/image.zip)
to some directory
- Create a build configuration with build step `Command Line`
- Specify the field `Run:` as `Executable with parameters`
- Specify the field `Command executable: ` as a full path to `image.cmd`
- Run a build for the created  build configuration
- Check test`s metadata

Also could you repeat steps above for [image1.zip](https://github.com/JetBrains/TeamCity.ServiceMessages/files/2791786/image1.zip)

**Comment by NikolayPianikov** [comment]
@olsh any updates?

**Comment by olsh** [comment]
Hi @NikolayPianikov 

Sorry for the delay, I didn't have time to test it.
We are using `PublishArtifact` which works for us just fine.
```csharp
                using (var writer = new TeamCityServiceMessages().CreateWriter())
                {
                    writer.PublishArtifact(imagePath + " => TearData");
                }
```

I think we can close the issue.

**Comment by NikolayPianikov** [comment]
@olsh thx
