### ISSUE TITLE
Duplicate entries when attaching images

### ISSUE THREAD

**Issue by Kamilbrd** [JetBrains/TeamCity.ServiceMessages#31]
Hello,

I was trying to attach screenshots to my teamcity test reports. All works fine but another entry with a status of 'OK' is created where the screenshot is attached, of course this makes the report unusable. I noticed that the scope in the entries does not match. 

The code I am using:
`using (var writer = new TeamCityServiceMessages().CreateWriter(Console.WriteLine))
                {
                    using (var test = writer.OpenTest(TestContext.CurrentContext.Test.FullName))
                    {
                        writer.PublishArtifact(screenshotFilePath + " => TestData");
                        test.WriteImage("TestData/" + screenshotFileName, screenshotFileName);
                    }
                }`

How the report looks, please note only 1 test was run and failed but the screenshot is attached to a separate entry: 
![Screenshot_96](https://user-images.githubusercontent.com/41578524/76543414-63b9cf80-647e-11ea-92b9-0219fbc2c648.png)

Perhaps I am doing something wrong here but I would expect the screenshot to be attached to the failed test in this case.
Thank you in advance for any help with this 

Edit: Some extra details
Using NUnit runner
Specflow 2.4
TC 2019.2

**Comment by kir** [comment]
Look like the generated test name does not include `OutlookTests.dll: ` suite name prefix.

**Comment by kir** [comment]
@NikolayPianikov Is there a simple fix for that?

**Comment by Kamilbrd** [comment]
Hi, 

I can confirm that by including the .dll filename the metadata is attached correctly to the failed test.

**Comment by NikolayPianikov** [comment]
@Kamilbrd most of known test frameworks support attachments, for instance the NUnit framework has the API call: `TestContext.AddTestAttachment(@"data\MyImage.gif");`
VSTest/MSTest has `TestContext.AddResultFile(@"data\MyImage.gif");`
So it is not needed to use _TeamCity.ServiceMessages_ library only to attach some artifacts. But you can use this library of course, but you should take in account a set of details depending on a selected test framework like the rule of test naming.

**Comment by Kamilbrd** [comment]
I tried `TestContext.AddTestAttachment` but it did not seem to have any effect, I will look into it as well.

**Comment by NikolayPianikov** [comment]
@Kamilbrd I've attached [the sample](https://github.com/JetBrains/TeamCity.ServiceMessages/files/4339595/abc.zip) for NUnit for 2 cases:
- full .net
- core .net

⚠️ It is important to note the attachments are supported in TeamCity since 2018.2

**Comment by NikolayPianikov** [comment]
@Kamilbrd Any updates? Did you manage what you want?

**Comment by Kamilbrd** [comment]
Hi, yes, thank you for the help, the workaround I mentioned earlier has worked, issue can be closed.
